variables:
  GOOGLE_PROJECT: "gb-poc-373711"
  GOOGLE_REGION: "europe-west1"
  PULUMI_BACKEND_URL: "gs://gb-poc-pulumi-state/bigtesty"
  BIGTESTY_STACK_NAME: "bigtesty"
  PULUMI_CONFIG_PASSPHRASE: "gcp_fake_passphrase"

stages:
  - tests

tests:
  stage: tests
  image:
    name: "mazlumtosun/bigtesty"
    entrypoint: [ "" ]
  when: manual
  script:
    - |
      bigtesty test \
        --root-test-folder $CI_PROJECT_DIR/examples/tests \
        --root-tables-folder $CI_PROJECT_DIR/examples/tests/tables \
        --tables-config-file $CI_PROJECT_DIR/examples/tests/tables/tables.json
