changelog:
  categories:
  - title: 💣 Breaking Changes
    labels:
    - breaking-change
  - title: 🚀 Features
    labels:
    - feature
  - title: 🐛 Bug Fixes
    labels:
    - bug
  - title: 📝 Documentation
    labels:
    - doc
  - title: 🧪 Tests
    labels:
    - test
  - title: 🛠️ Build
    labels:
    - build
