name: Deploy doc to GitHub Pages

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: bigtesty-doc

jobs:
  deploy-github-pages:
    name: Deploy Docusaurus doc GitHub Pages
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: bigtesty-doc/build

      - name: Deploy to GitHub Pages
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/deploy-pages@v4
