name: Docker

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

on:
  pull_request:
    branches: ['*']
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - bigtesty
        - bigtesty-deps
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: github.event_name == 'workflow_dispatch'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.target }}:latest
        target: ${{ matrix.target }}
        push: ${{ github.event_name == 'workflow_dispatch' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
