name: Publish Package PyPi

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.9.19

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install packages
      run: |
        pip install wheel
        pip install twine

    - name: Build dist
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish library to PyPi
      run: |
        python -m twine upload --verbose dist/*
      env:
        TWINE_USERNAME: ${{ vars.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
